config/routes.rb
Task::Application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'
  
  resources :rhs

  

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job_role.rb
class JobRole < ApplicationRecord
end

app/models/rh.rb
class Rh < ActiveRecord::Base
	#def self.search(query)
		
	scope :search, ->(query){ where("Nome like ?", "%#{query}%") }		
	validates_presence_of :Matricula, :Nome,:LotacaoDeTrabalho, :Cargo, :Telefone, :Celular, :Email #Este campo é obrigatório
	validates_uniqueness_of :Cargo and :LotacaoDeTrabalho 
	validates_uniqueness_of :Matricula , :Email #Este campo é único
	
end
	

app/models/workspace.rb
class Workspace < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rhs_controller.rb
class RhsController < ApplicationController
  before_action :set_rh, only: [:show, :edit, :update, :destroy]

  # GET /rhs
  # GET /rhs.json
  def index

    if params[:search]
      @rhs = Rh.search(params[:search]) 
    else     
    @rhs = Rh.order("Nome")
    end

  end

  # GET /rhs/1
  # GET /rhs/1.json
  def show
  end

  # GET /rhs/new
  def new
    @rh = Rh.new
  end

  # GET /rhs/1/edit
  def edit
  end

  # POST /rhs
  # POST /rhs.json
  def create
    @rh = Rh.new(rh_params)

    respond_to do |format|
      if @rh.save
        format.html { redirect_to @rh, notice: 'Rh was successfully created.' }
        format.json { render action: 'show', status: :created, location: @rh }
      else
        format.html { render action: 'new' }
        format.json { render json: @rh.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rhs/1
  # PATCH/PUT /rhs/1.json
  def update
    respond_to do |format|
      if @rh.update(rh_params)
        format.html { redirect_to @rh, notice: 'Rh was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rh.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rhs/1
  # DELETE /rhs/1.json
  def destroy
    @rh.destroy
    respond_to do |format|
      format.html { redirect_to rhs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rh
      @rh = Rh.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rh_params
      params.require(:rh).permit(:Matricula, :Nome, :Telefone, :Celular, :Email,:Nascimento, :MunicipioDeNascimento, :EstadoDeNascimento, :EstadoCivil, :Sexo, :LotacaoDeTrabalho, :Cargo)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/r_hs_helper.rb
module RHsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <title>Task</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
 	<%= stylesheet_link_tag "estilos" %>
</head>
<body>
<fieldset id="principal">
<%= yield %>
</fieldset>
</body>
</html>

app/views/rhs/_form.html.erb
<%= form_for(@rh) do |f| %>
  <% if @rh.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rh.errors.count, "error") %> prohibited this rh from being saved:</h2>

      <ul>
      <% @rh.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">*
    <%= f.label :Matricula  %>:
    <%= f.number_field :Matricula,placeholder:"Digite a matrícula", :size => 5  %>
  
    <%= f.label :Nome %>:
    <%= f.text_field :Nome, placeholder:"Digite o nome", :size => 35   %>

    Data de
    <%= f.label :Nascimento %>:
    <%= f.date_field :Nascimento %>
  </div> 

  <div class="field">
    *<%= f.label :Telefone %>:
    <%= f.text_field :Telefone,placeholder:"Digite o telefone", :size =>15 %>
 
    *<%= f.label :Celular %>:
    <%= f.text_field :Celular,placeholder:"Digite o celular", :size => 15 %>
  
    *<%= f.label :Email %>:
    <%= f.text_field :Email,placeholder:"Digite o email", :size => 54 %>
  </div>
  <div class="field">
    <%= f.label :Município_De_Nascimento %>:
    <%= f.text_field :MunicipioDeNascimento,placeholder:"Digite a municipio de nascimento", :size => 21 %>
  
    <%= f.label :Estado_De_Nascimento %>:
    <%= f.text_field :EstadoDeNascimento,placeholder:"Digite o estado de nascimento", :size => 20 %>
  
    <%= f.label :Estado_Civil %>:
    <%= f.select :EstadoCivil,['Solteiro(a)','Casado(a)','Divorciado(a)'] %>
  </div>
  <div class="field">
    <%= f.label :Sexo %>:
    <%= f.select :Sexo, ['Masculino','Feminino','Não Informado'] %>
 
    *<%= f.label :Lotação_De_Trabalho %>:
    <%= f.select :LotacaoDeTrabalho, ['','Área Sul','Área Norte','Área Leste','Área Oeste','1º Batalhão','2º Batalhão','3º Batalhão','4º Batalhão','Via Dultra','Comitiva do Anel','Guarita'] %>
  
    *<%= f.label :Cargo %>:
    <%= f.select :Cargo, ['','Programador','Suporte','Guarda','Tesoureiro','Camareira','Soldado','Gerente','Supervisor','Administrativo'] %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  (*) Campo Obrigatório
  
<% end %>

app/views/rhs/edit.html.erb
<%= stylesheet_link_tag "estilos" %>
<center><h1>Editar Pessoa</h1></center>
<fieldset id="edit">
<%= render 'form' %>

<%= link_to 'Mostar', @rh %> |
<%= link_to 'Voltar', rhs_path %>
</fieldset>

app/views/rhs/index.html.erb
<fieldset id="topo" ><legend><h3>Pesquisar</h3></legend>
 <center>
    <%= form_tag(rhs_path, :method => :get) do %>
    <%= text_field_tag 'search', nil,placeholder: 'Busca por nome ou matrícula', :size => 40%>
      <%= submit_tag "Search"%>
    <% end %>

    <%= link_to 'Cadastrar Pessoa', new_rh_path %></fieldset>
 </center>
 

 <fieldset id="media">
    <center>
     <table>

      <thead>
       <tr>       
          <th>Nome</th>
          <th>Matrícula </th>
          <th>Nascimento</th>     
          <th>Sexo</th>
          <th>Lotação de Trabalho</th>
          <th>Cargo</th>
          <th>Ações</th>
          <th></th>
          <th></th>
          <th></th>
       </tr>
      </thead>
       <tbody>
        <% @rhs.each do |rh| %>
          <tr>          
            <td><%= rh.Nome %></td>
            <td><%= rh.Matricula %></td>
            <td><%= rh.Nascimento %></td>    
            <td><%= rh.Sexo %></td>
            <td><%= rh.LotacaoDeTrabalho %></td>
            <td><%= rh.Cargo %></td>
            <td><%= link_to 'Mostar', rh %></td>
            <td><%= link_to 'Editar', edit_rh_path(rh) %></td>
            <td><%= link_to 'Deletar', rh, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
       </tbody>
      </table>
     </center>
 </fieldset>

 

app/views/rhs/new.html.erb
<%= stylesheet_link_tag "estilos" %>

<center><h2>Cadastrar pessoa</h2></center>

<fieldset id="new">
	

<%= render 'form' %>

<%= link_to 'Back', rhs_path %>

</fieldset>

app/views/rhs/show.html.erb
<p id="notice"><%= notice %></p>
<center><h2>Visualizar Pessoas</h2></center>
<fieldset id="mostrar">
<p>
  <strong>Matrícula:</strong>
  <%= @rh.Matricula %>

  <strong>Nome:</strong>
  <%= @rh.Nome %>

 <strong>Nascimento:</strong>
  <%= @rh.Nascimento %>

  <strong>Municipio de nascimento:</strong>
  <%= @rh.MunicipioDeNascimento %>
</p>
<p>
  <strong>Estadode Nascimento:</strong>
  <%= @rh.EstadoDeNascimento %>

  <strong>Estado Civil:</strong>
  <%= @rh.EstadoCivil %>

    <strong>Sexo:</strong>
  <%= @rh.Sexo %>
</p>
  <strong>Telefone:</strong>
  <%= @rh.Telefone %>
</p>
<p>
  <strong>Celular:</strong>
  <%= @rh.Celular %>
</p>
<p>
  <strong>Email:</strong>
  <%= @rh.Email %>
<p>
  <strong>Lotacao de trabalho:</strong>
  <%= @rh.LotacaoDeTrabalho %>
</p>
<p>
  <strong>Cargo:</strong>
  <%= @rh.Cargo %>
</p>

<%= link_to 'Edit', edit_rh_path(@rh) %> |
<%= link_to 'Back', rhs_path %>
</fieldset>

app/views/welcome/index.html.erb
<h1>Bem vindo!</h1>
<p><%= link_to "Rhs", rhs_path %></p>